[package]
name = "app_core"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
schemars.workspace = true
validator.workspace = true
uuid.workspace = true
thiserror.workspace = true
sqlx.workspace = true
config.workspace = true
dotenvy.workspace = true
